# ========================================
# despensaITU — Application Configuration (H2 RAM)
# ========================================

# Server
server.port=8080

# H2 In-Memory Database (RAM)
spring.datasource.url=jdbc:h2:mem:restaurante;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Crea y destruye las tablas automáticamente en memoria (ejecuta import.sql al iniciar)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar la Consola Web de H2 para depuración visual
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Diferir la inicialización de datos para que se ejecute después de crear las tablas
spring.jpa.defer-datasource-initialization=true

# Jackson (JSON)
spring.jackson.default-property-inclusion=non_null
